# General Parameters
use_scan_matching: true
use_scan_barycenter: true
minimum_travel_distance: 0.3 
minimum_travel_heading: 0.08726646259971647                #in radians
scan_buffer_size: 70
scan_buffer_maximum_scan_distance: 15.0
link_match_minimum_response_fine: 0.4
link_scan_maximum_distance: 6
loop_search_maximum_distance: 4.0
do_loop_closing: true
loop_match_minimum_chain_size: 10
loop_match_maximum_variance_coarse: 0.16    # gets squared later
loop_match_minimum_response_coarse: 0.7
loop_match_minimum_response_fine: 0.7

# Correlation Parameters - Correlation Parameters
correlation_search_space_dimension: 0.5
correlation_search_space_resolution: 0.01
correlation_search_space_smear_deviation: 0.03

# Correlation Parameters - Loop Closure Parameters
loop_search_space_dimension: 4.0
loop_search_space_resolution: 0.05
loop_search_space_smear_deviation: 0.03

# Scan Matcher Parameters
distance_variance_penalty: 0.09             # gets squared later
angle_variance_penalty: 0.1218469679146834                # in degrees (gets converted to radians then squared)
fine_search_angle_offset: 0.00349               # in degrees (gets converted to radians)
coarse_search_angle_offset: 0.349            # in degrees (gets converted to radians)
coarse_angle_resolution: 0.0349                # in degrees (gets converted to radians)
minimum_angle_penalty: 0.9
minimum_distance_penalty: 0.5
use_response_expansion: false
